### ISSUE TITLE
Question about licensing and derivatives

### ISSUE THREAD

**Issue by jma1991** [Bioconductor/OrchestratingSingleCellAnalysis#56]
I am building a [Snakemake workflow](https://github.com/jma1991/orchestra) to analyse scRNA-seq data and would like to make it available through the Snakemake workflows repository. However, because the workflow itself is based on the material in the OSCA book I am not sure whether this is allowed under the current license:

"NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material."

If this use-case is not covered by the license, is it recommended that I do not share the workflow and instead make the repository private?

**Comment by LTLA** [comment]
I'm pretty sure the current license is a mistake; such restrictions were not intentional. Probably someone got over-enthusiastic about choosing licenses and picked an unusually specific one. I mean, in principle, the non-commercial aspect means that I can't even use my own content, which would be ridiculous.

The next version will be using CC BY 4.0 - check out [this](https://bioconductor.org/books/3.13/OSCA/https://bioconductor.org/books/3.13/OSCA/) (currently missing the 4.0, but I'll add that in later).

**Comment by jma1991** [comment]
That's great news, thank you all very much.
