### ISSUE TITLE
any(seqnames(location)=="MT") question

### ISSUE THREAD

**Issue by tiagochst** [Bioconductor/OrchestratingSingleCellAnalysis#60]
I just want to double-check this part of the code at [OSCA devel - quality control](http://bioconductor.org/books/3.13/OSCA.basic/quality-control.html#common-choices-of-qc-metrics):

`is.mito <- any(seqnames(location)=="MT")` will give me only a `TRUE`. 

However, I understood this should be a vector or index of features. In that case, this should be 
 `is.mito <- which(seqnames(location)=="MT")` ?

<img width="1436" alt="Screen Shot 2021-07-09 at 12 50 33 PM" src="https://user-images.githubusercontent.com/145529/125111815-5d5c5780-e0b4-11eb-90d3-da10b892206a.png">

**Comment by LTLA** [comment]
This depends on whether your `location` is a `GRanges` or `GRangesList`. For `sce.416b`, it's the latter, so the `any()` function will yield a vector (because the boolean ANY applies within each GRL entry, rather than across GRL entries). If you just have a `GRanges`, it's more appropriate to do `which()`; I believe that this is done for some of the other datasets.

Ideally, we would have a representation-agnostic way of getting this kind of vector, regardless of whether the input is a GR or GRL. I proposed this in Bioconductor/GenomicRanges#52 but it looks like there hasn't been much appetite for this.

**Comment by tiagochst** [comment]
Thanks!
